import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next/types";
import { getLicenseList } from "../../service/licenseService";
import { LicenseList } from "../../types/license";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: LicenseList) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {data &&
          React.Children.toArray(
            data.map(
              ({
                customerName,
                customerEmail,
                domain,
                shopId,
                licenseKey,
              }: LicenseList) => {
                return (
                  <ul>
                    <li>{customerName}</li>
                    <li>{customerEmail}</li>
                    <li>{domain}</li>
                    <li>{shopId}</li>
                    <li>{licenseKey}</li>
                  </ul>
                );
              }
            )
          )}
      </main>
    </>
  );
}
export const getStaticProps: GetStaticProps = async () => {
  const data = await getLicenseList();
  return {
    props: {
      data,
    },
  };
};
